name = "email-worker-summarize"
main = "src/worker.ts"
compatibility_date = "2025-02-05"
compatibility_flags = ["nodejs_compat"]

[vars]
PUSHOVER_API_URL = "https://api.pushover.net/1/messages.json"
TELEGRAM_TO_CHAT_ID = "-4706038643"
EMAIL_ALLOWLIST = "jimzenn0@gmail.com,*@zenn.in,cplusherly@gmail.com"
GOOGLE_CALENDAR_ID = "c_1cdf51574bb6ac183721c99fae8dc7deba72c48fe0e0c7e892f26b6c974cd15c@group.calendar.google.com"

OPENAI_MODEL = "gpt-4o-2024-08-06"
OPENAI_REASONING_MODEL = "gpt-4o-2024-08-06"

GEMINI_MODEL = "gemini-2.5-pro"
GEMINI_REASONING_MODEL = "gemini-2.5-pro"

DEEPSEEK_MODEL = "deepseek-chat"
DEEPSEEK_REASONING_MODEL = "deepseek-reasoner"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "962c4ad686554b0fa1ecbb8c2664b3bd"
preview_id = "temp_preview_id"